apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-env-configmap
  labels:
    app: nextcloud
data:
  NEXTCLOUD_UPDATE: "1"
  ALLOW_EMPTY_PASSWORD: "yes"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_DB: "postgres"
  NEXTCLOUD_TRUSTED_DOMAINS: "127.0.0.1"